apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AZURE_CLIENT_ID
          value: {{ .Values.env.azureClientId }}
        - name: AZURE_CLIENT_KEY
          value: {{ .Values.env.azureClientKey }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.env.azureTenantId }}
        - name: AZURE_SUBSCRIPTION_ID
          value: {{ .Values.env.azureSubscriptionId }}
        - name: ACI_RESOURCE_GROUP
          value: {{ .Values.env.aciResourceGroup }}
        - name: ACI_REGION
          value: {{ default "westus" .Values.env.aciRegion }}
