apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
type: Opaque
data:
  azure-sp-client-id: {{ default "MISSING" .Values.env.azureClientId | b64enc | quote }}
  azure-sp-client-key: {{ default "MISSING" .Values.env.azureClientKey | b64enc | quote }}
  azure-sp-tenant-id: {{ default "MISSING" .Values.env.azureTenantId | b64enc | quote }}
  azure-subscription-id: {{ default "MISSING" .Values.env.azureSubscriptionId | b64enc | quote }}
